-- MySQL Script generated by MySQL Workbench
-- Fri Apr 11 21:59:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pixup
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pixup` ;

-- -----------------------------------------------------
-- Schema pixup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pixup` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `pixup` ;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_ESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_ESTADO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_ESTADO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ESTADO` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_MUNICIPIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_MUNICIPIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_MUNICIPIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MUNICIPIO` VARCHAR(30) NOT NULL,
  `TBL_ESTADO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TBL_MUNICIPIO_TBL_ESTADO_idx` (`TBL_ESTADO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_MUNICIPIO_TBL_ESTADO`
    FOREIGN KEY (`TBL_ESTADO_ID`)
    REFERENCES `pixup`.`TBL_ESTADO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_COLONIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_COLONIA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_COLONIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COLONIA` VARCHAR(50) NOT NULL,
  `CP` VARCHAR(5) NOT NULL,
  `TBL_MUNICIPIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TBL_COLONIA_TBL_MUNICIPIO1_idx` (`TBL_MUNICIPIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_COLONIA_TBL_MUNICIPIO1`
    FOREIGN KEY (`TBL_MUNICIPIO_ID`)
    REFERENCES `pixup`.`TBL_MUNICIPIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_ARTISTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_ARTISTA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_ARTISTA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ARTISTA` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_DISQUERA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_DISQUERA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_DISQUERA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DISQUERA` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_GENERO_MUSICAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_GENERO_MUSICAL` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_GENERO_MUSICAL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `GENERO` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_DISCO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_DISCO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_DISCO` (
  `ID` INT NULL AUTO_INCREMENT,
  `TITULODISCO` VARCHAR(200)  NULL,
  `PRECIO` DECIMAL(5,2)  NULL,
  `EXISTENCIA` INT  NULL,
  `DESCUENTO` DOUBLE  NULL,
  `FECHA_LANZAMIENTO` DATE  NULL,
  `IMAGEN` VARCHAR(120)  NULL,
  `TBL_ARTISTA_ID` INT  NULL,
  `TBL_DISQUERA_ID` INT  NULL,
  `TBL_GENERO_MUSICAL_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TBL_DISCO_TBL_ARTISTA1_idx` (`TBL_ARTISTA_ID` ASC) VISIBLE,
  INDEX `fk_TBL_DISCO_TBL_DISQUERA1_idx` (`TBL_DISQUERA_ID` ASC) VISIBLE,
  INDEX `fk_TBL_DISCO_TBL_GENERO_MUSICAL1_idx` (`TBL_GENERO_MUSICAL_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_DISCO_TBL_ARTISTA1`
    FOREIGN KEY (`TBL_ARTISTA_ID`)
    REFERENCES `pixup`.`TBL_ARTISTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DISCO_TBL_DISQUERA1`
    FOREIGN KEY (`TBL_DISQUERA_ID`)
    REFERENCES `pixup`.`TBL_DISQUERA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DISCO_TBL_GENERO_MUSICAL1`
    FOREIGN KEY (`TBL_GENERO_MUSICAL_ID`)
    REFERENCES `pixup`.`TBL_GENERO_MUSICAL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_CANCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_CANCION` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_CANCION` (
  `ID` INT NULL AUTO_INCREMENT,
  `TITULOCANCION` VARCHAR(200) NULL,
  `DURACION` TIME NULL,
  `TBL_DISCO_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TBL_CANCION_TBL_DISCO1_idx` (`TBL_DISCO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_CANCION_TBL_DISCO1`
    FOREIGN KEY (`TBL_DISCO_ID`)
    REFERENCES `pixup`.`TBL_DISCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
